[package]
name = "rustc_apfloat"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
smallvec = { git = "https://github.com/the8472/rust-smallvec.git", branch = "delegate-vec-extend-from", features = ["union", "may_dangle"] }
