[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { version = "0.1.0", features = ['rustc-dep-of-std'] }

[build-dependencies]
cc = "1.0.97"

[patch.crates-io]
compiler_builtins = { git = "https://github.com/tgross35/compiler-builtins.git", rev = "ae00838dc9deefec686f282024acbaee8f289735"}
