[package]
name = "tidy"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
cargo_metadata = "0.15"
cargo-platform = "0.1.2"
regex = "1"
miropt-test-tools = { path = "../miropt-test-tools" }
lazy_static = "1"
walkdir = "2"
ignore = "0.4.18"
semver = "1.0"
termcolor = "1.1.3"
test_common = { path = "../test_common" }

[[bin]]
name = "rust-tidy"
path = "src/main.rs"
