[package]
authors = ["The Rust Project Developers"]
name = "std"
version = "0.0.0"
build = "build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang/rust.git"
description = "The Rust Standard Library"

[lib]
name = "std"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
alloc_jemalloc = { path = "../liballoc_jemalloc", optional = true }
alloc_system = { path = "../liballoc_system" }
panic_unwind = { path = "../libpanic_unwind", optional = true }
panic_abort = { path = "../libpanic_abort" }
libc = { path = "../rustc/libc_shim" }
profiler_builtins = { path = "../libprofiler_builtins", optional = true }
unwind = { path = "../libunwind" }
object = { version = "0.9", default-features = false, optional = true }

[dependencies.gimli]
version = "0.16"
default-features = false
features = ["alloc"]
git = "https://github.com/est31/gimli"
rev = "304caacf8b73f117813b1a0d436ce24403459bf2"
optional = true

[dependencies.addr2line]
git = "https://github.com/est31/addr2line"
branch = "no_std_prototype"
default-features = false
features = ["cpp_demangle"]
optional = true

[dev-dependencies]
rand = "0.4"

[target.x86_64-apple-darwin.dependencies]
rustc_asan = { path = "../librustc_asan" }
rustc_tsan = { path = "../librustc_tsan" }

[target.x86_64-unknown-linux-gnu.dependencies]
rustc_asan = { path = "../librustc_asan" }
rustc_lsan = { path = "../librustc_lsan" }
rustc_msan = { path = "../librustc_msan" }
rustc_tsan = { path = "../librustc_tsan" }

[build-dependencies]
cc = "1.0"
build_helper = { path = "../build_helper" }

[features]
backtrace = ["addr2line", "object", "gimli"]
debug-jemalloc = ["alloc_jemalloc/debug"]
jemalloc = ["alloc_jemalloc"]
force_alloc_system = []
panic-unwind = ["panic_unwind"]
profiler = ["profiler_builtins"]
wasm_syscall = []
