[package]
name = "rustc_codegen_ssa"
version = "0.0.0"
edition = "2021"

[lib]
test = false

[dependencies]
bitflags = "1.3.2"
cc = "1.0.77"
itertools = "0.10.5"
tracing = "0.1"
libc = "0.2.137"
jobserver = "0.1.25"
tempfile = "3.3"
thorin-dwp = "0.3"
pathdiff = "0.2.1"
serde_json = "1.0.89"
snap = "1"
smallvec = { version = "1.10.0", features = ["union", "may_dangle"] }
regex = "1.7"

rustc_serialize = { path = "../rustc_serialize" }
rustc_arena = { path = "../rustc_arena" }
rustc_ast = { path = "../rustc_ast" }
rustc_span = { path = "../rustc_span" }
rustc_middle = { path = "../rustc_middle" }
rustc_attr = { path = "../rustc_attr" }
rustc_symbol_mangling = { path = "../rustc_symbol_mangling" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_errors = { path = "../rustc_errors" }
rustc_fs_util = { path = "../rustc_fs_util" }
rustc_hir = { path = "../rustc_hir" }
rustc_incremental = { path = "../rustc_incremental" }
rustc_index = { path = "../rustc_index" }
rustc_macros = { path = "../rustc_macros" }
rustc_metadata = { path = "../rustc_metadata" }
rustc_query_system = { path = "../rustc_query_system" }
rustc_target = { path = "../rustc_target" }
rustc_session = { path = "../rustc_session" }
rustc_const_eval = { path = "../rustc_const_eval" }

[dependencies.object]
version = "0.29.0"
default-features = false
features = ["read_core", "elf", "macho", "pe", "unaligned", "archive", "write"]
