language: generic
sudo: required
services:
  - docker

# LLVM takes awhile to check out and otherwise we'll manage the submodules
# ourselves, so disable auto submodule management.
git:
  submodules: false
  depth: 1

# We want to mount source directory read-only to test out-of-tree build.
# This means configure can't manage submodules, so we do it here.
before_install:
  - git submodule init
  - git submodule deinit src/llvm
  - git submodule update
  - docker build -t rust -f src/etc/Dockerfile src/etc

script:
  - docker run -v `pwd`:/src:ro rust
    sh -c "
      /src/configure
        --llvm-root=/usr/lib/llvm-3.7
        --disable-manage-submodules &&
      make tidy &&
      make check-notidy -j4
    "

# Real testing happens on http://buildbot.rust-lang.org/
#
# See https://github.com/rust-lang/rust-buildbot
#     CONTRIBUTING.md#pull-requests

notifications:
  email: false

branches:
  only:
    - master
