language: generic
sudo: required
dist: trusty

# LLVM takes awhile to check out and otherwise we'll manage the submodules in
# our configure script, so disable auto submodule management.
git:
  submodules: false

before_install:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/lo/disable_ipv6
  - sudo apt-get update
  - sudo apt-get --force-yes install curl make g++ python2.7 git

script:
  - ./configure --enable-ccache
  - make tidy && make check-notidy -j4

cache:
  directories:
    - $HOME/.ccache

# Real testing happens on http://buildbot.rust-lang.org/
#
# See https://github.com/rust-lang/rust-buildbot
#     CONTRIBUTING.md#pull-requests

notifications:
  email: false

branches:
  only:
    - master
