[package]
name = "rustc_driver"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# tidy-alphabetical-start
fjall = { git = "https://github.com/Zoxc/fjall.git" }
rustc_driver_impl = { path = "../rustc_driver_impl" }
# tidy-alphabetical-end
