[workspace]
resolver = "1"
members = [
    "crates/core_simd",
    "crates/std_float",
    "crates/test_helpers",
]

[patch.crates-io]
compiler_builtins = { git = "https://github.com/tgross35/compiler-builtins.git", rev = "e7fd5be54ae5b636d16de041e6700c80624131bf" }
