[workspace]
resolver = "1"
members = [
    "crates/core_simd",
    "crates/std_float",
    "crates/test_helpers",
]

[patch.crates-io]
compiler_builtins = { git = "https://github.com/tgross35/compiler-builtins.git", branch = "libm-sse-fix"}
