[package]
name = "rust_builtin"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "rust_builtin"
build = "build.rs"

[lib]
name = "rust_builtin"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
