[package]
authors = ["The Rust Project Developers"]
name = "serialize"
version = "0.0.0"

[lib]
name = "serialize"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
ordermap = { path = "../ordermap" }
