[package]
authors = ["The Rust Project Developers"]
name = "serialize"
version = "0.0.0"

[lib]
name = "serialize"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
log = { path = "../liblog" }
rustc_unicode = { path = "../librustc_unicode" }
collections = { path = "../libcollections" }
std = { path = "../libstd" }

[dev-dependencies]
test = { path = "../libtest" }
