[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "1"
smallvec = { git = "https://github.com/the8472/rust-smallvec.git", branch = "delegate-vec-extend-from", features = ["union", "may_dangle"] }

[dev-dependencies]
rustc_macros = { path = "../rustc_macros" }
