[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "1.9.1"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = { git = "https://github.com/nnethercote/thin-vec", branch = "u32-len-cap", features = ["u32-len-cap"] }

[dev-dependencies]
rustc_macros = { path = "../rustc_macros" }
