[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "1.7.0"
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }

[dev-dependencies]
rustc_macros = { path = "../rustc_macros" }
