[package]
name = "system"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "system"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
libc = { path = "../liblibc" }
alloc = { path = "../liballoc" }
rand = { path = "../librand" }
collections = { path = "../libcollections" }
rustc_unicode = { path = "../librustc_unicode" }
rustc_bitflags = { path = "../librustc_bitflags" }
rust_builtin = { path = "deps/rust_builtin", optional = true }
backtrace = { path = "deps/backtrace", optional = true }
compiler-rt = { path = "deps/compiler-rt", optional = true }

[features]
default = ["backtrace", "compiler-rt", "rust_builtin"]
disable-backtrace = []
