[package]
authors = ["The Rust Project Developers"]
name = "rustc_coverage"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_coverage"
path = "lib.rs"

[dependencies]
log = "0.4"
rustc_errors = { path = "../librustc_errors" }
rustc_resolve = { path = "../librustc_resolve" }
rustc_ast = { path = "../librustc_ast" }
rustc_span = { path = "../librustc_span" }
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
