[package]
name = "rustc_data_structures"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
arrayvec = { version = "0.7", default-features = false }
bitflags = "1.3.2"
cfg-if = "1.0.0"
ena = "0.14"
indexmap = { version = "1.9.2" }
jobserver_crate = { version = "0.1.25", package = "jobserver" }
libc = "0.2"
measureme = "10.1.0"
rayon-core = { version = "0.4.1", package = "rustc-rayon-core", optional = true }
rayon = { version = "0.4.0", package = "rustc-rayon", optional = true }
rustc_graphviz = { path = "../rustc_graphviz" }
rustc-hash = "1.1.0"
rustc_index = { path = "../rustc_index", package = "rustc_index" }
rustc_macros = { path = "../rustc_macros" }
rustc_serialize = { path = "../rustc_serialize" }
smallvec = { version = "1.10.0", features = ["const_generics", "union", "may_dangle"] }
stable_deref_trait = "1.2.0"
stacker = "0.1.15"
tempfile = "3.3"
thin-vec = "0.2.9"
tracing = "0.1"

[dependencies.parking_lot]
version = "0.12"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["fileapi", "psapi", "winerror"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memmap2 = "0.5.8"

[features]
rustc_use_parallel_compiler = ["indexmap/rustc-rayon", "rayon", "rayon-core"]
