[package]
name = "rustc_borrowck"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "rustc_borrowck"
path = "lib.rs"

[dependencies]
graphviz = { path = "../libgraphviz" }
rustc = { path = "../librustc" }
rustc_front = { path = "../librustc_front" }
log = { path = "../liblog" }
syntax = { path = "../libsyntax" }
