[package]
authors = ["The Rust Project Developers"]
name = "rustc_data_structures"
version = "0.0.0"

[lib]
name = "rustc_data_structures"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = "0.3"
serialize = { path = "../libserialize" }
cfg-if = "0.1.2"
owning_ref = { git = "https://github.com/Zoxc/owning-ref-rs.git" }

[dependencies.parking_lot]
version = "0.5"
features = ["nightly"]