[package]
authors = ["The Rust Project Developers"]
name = "rustc_apfloat"
version = "0.0.0"

[lib]
name = "rustc_apfloat"
path = "lib.rs"

[dependencies]
bitflags = "1.0"
smallvec = { version = "0.6.7", features = ["union", "may_dangle"] }
