[package]
authors = ["The Rust Project Developers"]
name = "core"
version = "0.0.0"

[lib]
name = "core"
path = "lib.rs"
test = false
bench = false

[dependencies]
bitflags = "1.0"
rustc_cratesio_shim = { path = "../librustc_cratesio_shim" }

[dev-dependencies]
rand = { path = "../librand" }

[[test]]
name = "coretests"
path = "../libcore/tests/lib.rs"

[[bench]]
name = "corebenches"
path = "../libcore/benches/lib.rs"
