[package]
name = "coretest"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "coretest"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
test = { path = "../libtest" }
libc = { path = "../liblibc" }
rustc_unicode = { path = "../librustc_unicode" }
rand = { path = "../librand" }
