[package]
authors = ["The Rust Project Developers"]
name = "rustc_llvm"
version = "0.0.0"
build = "build.rs"

[lib]
name = "rustc_llvm"
path = "lib.rs"
crate-type = ["dylib"]

[features]
rebuild-bindings = ["bindgen"]

[build-dependencies]
# https://github.com/rust-lang-nursery/rust-bindgen/pull/1162.
bindgen = { git = "https://github.com/rust-lang-nursery/rust-bindgen.git", rev = "75f9e1c", optional = true }
cc = "1.0.1"
build_helper = { path = "../build_helper" }
