[package]
name = "rustc_llvm"
version = "1.0.0"
authors = ["The Rust Project Developers"]
build = "build.rs"

[lib]
name = "rustc_llvm"
path = "lib.rs"

[dependencies]
libc = { path = "../liblibc" }
rustc_bitflags = { path = "../librustc_bitflags" }

[build-dependencies]
gcc = "0.3"
