[package]
authors = ["The Rust Project Developers"]
name = "rustc_save_analysis"
version = "0.0.0"

[lib]
name = "rustc_save_analysis"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = "0.3"
rustc = { path = "../librustc" }
syntax = { path = "../libsyntax" }
serialize = { path = "../libserialize" }
syntax_pos = { path = "../libsyntax_pos" }
