[package]
name = "rustc_ast_pretty"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
itertools = { git = "https://github.com/rust-itertools/itertools" }
rustc_ast = { path = "../rustc_ast" }
rustc_lexer = { path = "../rustc_lexer" }
rustc_span = { path = "../rustc_span" }
thin-vec = "0.2.12"
# tidy-alphabetical-end
