[package]
name = "backtrace"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "backtrace"
build = "build.rs"

[lib]
name = "backtrace"
path = "lib.rs"

[build-dependencies]
gcc = { git = "https://github.com/alexcrichton/gcc-rs.git" }
