[package]
authors = ["The Rust Project Developers"]
name = "rustc_codegen_llvm"
version = "0.0.0"

[lib]
name = "rustc_codegen_llvm"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
cc = "1.0.1"
rustc-demangle = "0.1.4"
rustc_llvm = { path = "../librustc_llvm" }

# not actually used but needed to make sure we enable the same feature set as
# winapi used in librustc
env_logger = { version = "0.5", default-features = false }

[features]
# This is used to convince Cargo to separately cache builds of `rustc_codegen_llvm`
# when this option is enabled or not. That way we can build two, cache two
# artifacts, and have nice speedy rebuilds.
emscripten = ["rustc_llvm/emscripten"]
