[package]
authors = ["The Rust Project Developers"]
name = "rustc_resolve"
version = "0.0.0"

[lib]
name = "rustc_resolve"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
log = { path = "../liblog" }
syntax = { path = "../libsyntax" }
rustc_bitflags = { path = "../librustc_bitflags" }
rustc = { path = "../librustc" }
std = { path = "../libstd" }
