[package]
authors = ["The Rust Project Developers"]
name = "test"
version = "0.0.0"

[lib]
name = "test"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
std = { path = "../libstd" }
getopts = { path = "../libgetopts" }
serialize  = { path = "../libserialize" }
term = { path = "../libterm" }
libc = { path = "../liblibc" }
