[package]
authors = ["The Rust Project Developers"]
name = "alloc_frame"
version = "0.0.0"

[lib]
name = "alloc_frame"
path = "lib.rs"
test = false

[dependencies]
core = { path = "../libcore" }
libc = { path = "../rustc/libc_shim" }
