[package]
name = "rustc_feature"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
directories = "5.0"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_span = { path = "../rustc_span" }
time = { version = "0.3", default-features = false, features = ["alloc", "formatting"] }
# tidy-alphabetical-end
