[package]
name = "rustc_feature"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_index = { path = "../rustc_index" }
rustc_span = { path = "../rustc_span" }
# tidy-alphabetical-end
